[package]
name = "tablefy_derive"
version = "0.1.0"
authors = ["Calmynt <mctech26@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version = "0.15.41", features = ["extra-traits"]}
quote = "0.6.13"